### ISSUE TITLE
Error using --simplification option

### ISSUE THREAD

**Issue by liammachado** [michael-emmi/bam-bam-boogieman#10]
I am trying to use this tool to reduce a boogie file to a smaller size. However, currently if I run "bam test.bpl --simplification -o test2.bpl" and then run "bam test2.bpl", I receive the following message: "Error: parse error at token const on line 103". Is there a step I'm missing in running this option, or is this a bug? Also, what other options are there for reducing the size of boogie files besides "--pruning" and "--simplification"? And is there a specific order in which I should run these options?

**Comment by liammachado** [comment]
Here are test.bpl and test2.bpl.

[test.zip](https://github.com/michael-emmi/bam-bam-boogieman/files/1647768/test.zip)

**Comment by michael-emmi** [comment]
Hey @liammachado just fixed this in a9c1b1b
